Update patch set 1
Patch Set 1: -Verified -Autosubmit

CtsSelinuxTargetSdk27TestCases and CtsSelinuxTargetSdk28TestCases fail due to the unconditional mprotect at https://android-review.googlesource.com/c/platform/external/boringssl/+/1127318/1/src/crypto/fipsmodule/bcm.c#181

junit.framework.AssertionFailedError: System provided libraries should be not be marked execute-only for apps with targetSdkVersion<Q, but an execute-only segment was found:
e6bea000-e6bff000 --xp 000d0000 fc:00 1798                               /system/lib/libcrypto.so

The Zygote already has logic to disable XOM on system libraries for apps with targetSdkVersion<Q[1] which apparently isn't finding this one. However, there's also an argument that libcrypto should be exempt anyway on FIPS build.  I'll raise a bug to clarify.

[1] https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/com/android/internal/os/Zygote.java#699

Patch-set: 1
Reviewer: Gerrit User 1334152 <1334152@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0
Label: Autosubmit=0
Label: Presubmit-Ready=0