Disable boringssl_*_test for vendor
The tests inherit from boringssl_flags where vendor_available is set to
true. The tests however don't need to be built for vendor. Furthermore,
when the build system is changed so that __ANDROID_API__ tracks
min_sdk_version, the vendor variant of the test fails to build with the
following error:

external/boringssl/src/crypto/impl_dispatch_test.cc
In file included from
external/boringssl/src/crypto/impl_dispatch_test.cc:15:
In file included from external/boringssl/src/include/openssl/base.h:469:
In file included from external/libcxx/include/memory:654:
In file included from external/libcxx/include/typeinfo:61:
In file included from external/libcxx/include/exception:82:
external/libcxx/include/cstdlib:155:9: error: no member named
'at_quick_exit' in the global namespace
using ::at_quick_exit;

This happens because the vendor variant is built with __ANDROID_API__ ==
9 where at_quick_exit is not defined (it's added with SDK 21).

Bug: 163288375
Test: m
Change-Id: I79329128c0481b6bc1830096731eca84deb1113b